project:
  type: website

lang: es

website:
  title: "Grupo de Biología Computacional"
  navbar:
    right:
      - url: integrantes.md
        icon: people-fill
      - url: proyectos.qmd
        text: 'Proyectos'
        icon: terminal-fill
      - url: club-de-revista.qmd
        icon: easel3-fill

      - text: 'Cursos'
        icon: journal-code
        menu:
          - text: 'Cursos y talleres'
            url: cursos/cursos.md
            icon: laptop
          - text: 'Curso Linux'
            url: cursos/curso-linux.md
            icon: terminal
          - text: '{{< fa brands python >}} Curso Python'
            url: cursos/curso-python.md
          - url: cursos/material-educativo.qmd

      - text: 'Posts'
        url: posts.md
        icon: pencil-square
      - text: 'Noticias'
        url: news.md
        icon: newspaper
    tools:
      - icon: envelope-fill
        href: "mailto:biologiacomputacional42@gmail.com"
        text: Envíanos un email
      - icon: mastodon
        href: "https://mastodon.social/@biocomputacional"
        text: Síguenos en Mastodon
      - icon: telegram
        href: "https://t.me/biologia_computacional"
        text: Únete a nuestro grupo en Telegram
      - icon: twitter
        href: "https://twitter.com/biocomp42"
        text: Síguenos en Twitter
      - icon: facebook
        href: "https://www.facebook.com/groups/biologiacomputacional"
        text: Síguenos en Facebook
      - icon: github
        href: "https://github.com/Biologia-Computacional"
        text: Mira nuestro GitHub

  margin-header: |
    ![](/imgs/profile.png)
  favicon: /imgs/favicon.png
  twitter-card:
    creator: "@Nesper94"
  back-to-top-navigation: true

  comments:
    utterances:
      repo: Biologia-Computacional/Biologia-Computacional.github.io

  page-footer:
    right: Hecho por [Juan C. Arboleda R.](https://nesper94.github.io) con [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

format:
  html:
    theme:
      light: [flatly, font.scss]
      dark: [cyborg, font.scss]
    css: styles.css
    toc: true
    link-external-newwindow: true
    lightbox: true
