project:
  type: website

lang: es

website:
  title: "Grupo de Biología Computacional"
  navbar:
    left:
      - href: index.qmd
        text: Quiénes somos
      - proyectos.qmd
      - club-de-revista.md
      - cursos.md
      - posts.md
    tools:
      - icon: envelope-fill
        href: mailto:biologiacomputacional42@gmail.com
        text: Envíanos un email
      - icon: mastodon
        href: https://mastodon.social/@biocomputacional
        text: Síguenos en Mastodon
      - icon: telegram
        href: https://t.me/biologia_computacional
        text: Únete a nuestro grupo en Telegram
      - icon: twitter
        href: https://twitter.com/biocomp42
        text: Síguenos en Twitter
      - icon: facebook
        href: https://www.facebook.com/groups/biologiacomputacional
        text: Síguenos en Facebook
      - icon: github
        href: https://github.com/Biologia-Computacional
        text: Mira nuestro GitHub
  margin-header: |
    ![](/imgs/profile.png)
  favicon: /imgs/favicon.png
  twitter-card:
    creator: "@Nesper94"
  back-to-top-navigation: true

format:
  html:
    theme:
      light: flatly
      dark: cyborg
    css: styles.css
    toc: true

