project:
  type: website

lang: es

website:
  title: "Grupo de Biología Computacional"
  navbar:
    left:
      - url: integrantes.md
        icon: people-fill
      - url: proyectos.qmd
        icon: terminal-fill
      - url: club-de-revista.md
        icon: easel3-fill
      - text: 'Cursos'
        icon: journal-code
        menu:
          - cursos/cursos.md
          - text: 'Curso Linux'
            url: cursos/curso-linux.md
            icon: terminal
          - text: 'Curso Python'
            url: cursos/curso-python.md
            icon: code
      - url: posts.md
        icon: pencil-square
    tools:
      - icon: envelope-fill
        href: mailto:biologiacomputacional42@gmail.com
        text: Envíanos un email
      - icon: mastodon
        href: https://mastodon.social/@biocomputacional
        text: Síguenos en Mastodon
      - icon: telegram
        href: https://t.me/biologia_computacional
        text: Únete a nuestro grupo en Telegram
      - icon: twitter
        href: https://twitter.com/biocomp42
        text: Síguenos en Twitter
      - icon: facebook
        href: https://www.facebook.com/groups/biologiacomputacional
        text: Síguenos en Facebook
      - icon: github
        href: https://github.com/Biologia-Computacional
        text: Mira nuestro GitHub
  margin-header: |
    ![](/imgs/profile.png)
  favicon: /imgs/favicon.png
  twitter-card:
    creator: "@Nesper94"
  back-to-top-navigation: true

format:
  html:
    theme:
      light: flatly
      dark: cyborg
    css: styles.css
    toc: true

