project:
  type: website

website:
  title: "Biología-computacional"
  navbar:
    left:
      - href: index.qmd
        text: Quiénes somos
      - proyectos.qmd
      - club-de-revista.md
      - cursos.md

format:
  html:
    theme: cosmo
#    theme: minty
    css: styles.css
    toc: true

