# ¡Bienvenido al Grupo de Biología Computacional!

A continuación encontrarás las pautas para participar en el grupo.

## Reuniones del grupo

Las reuniones del grupo son de altísima importancia, y brindan la
oportunidad de resolver problemas juntos y de compartir y discutir ideas.
En nuestra reunión de grupo generalmente discutimos asuntos sobre los
proyectos del grupo, hacemos ensayos de presentaciones, presentamos y
discutimos nuevos resultados que hayamos obtenido, socializamos problemas
con los que nos hayamos encontrado o simplemente discutimos asuntos internos
del grupo.

Esta es la información sobre la reunión del grupo para el semestre
**2024-1**:

**Hora:** Viernes 12:00 - 14:00\
**Lugar:** Salón 7-325, Instituto de Biología, Universidad de Antioquia

## Guía de conducta

Como parte del grupo se espera que tú:

1. Asistas al Club de Revista y a las demás reuniones del grupo. Estos
   espacios son extremadamente importantes. Igualmente, se espera que avises
   **oportunamente** si no puedes asistir a algún encuentro.

1. Además de asistir, se espera que participes activamente en las reuniones.
   No tienes que saberlo todo, pero sí eres responsable de preguntar cuando
   no entiendas algo. Tus contribuciones son valiosas, tu perspectiva es
   diferente a la de cualquier otro y queremos escucharte.

1. Seas respetuoso en las reuniones. Debes poner atención, ser amable, y no
   distraerte jugando o mirando el celular.

1. Presentes artículos en el [Club de Revista](club-de-revista.qmd).

1. Manifiestes tus opiniones con libertad, en particular, si tienes
   propuestas u opinas que hay cosas que deben mejorar, esperamos que lo
   digas abiertamente.

1. Tengas iniciativa. Necesitamos personas innovadoras, con ganas de hacer
   cosas, ya sea de investigación, de divulgación de la ciencia, o preprar
   una gran fiesta. No queremos "zombies" que solo estén presentes sin
   aportar nada.

1. Busques y leas artículos de investigación y los compartas con los demás.

1. Si tienes asignada una tarea, asegúrate de hacerla a tiempo y de manera
   diligente.

1. Seas organizado con tu trabajo y **tengas una bitácora** donde reportes
   todo tu proceso de investigación y tus análisis.

1. Seas comunicativo y compartas tus pasiones e intereses. También es muy
   importante que comuniques si tienes problemas, así te podemos ayudar.

Por último, se te pedirá dejar el grupo si:

1. Acumulas tres faltas injustificadas a las reuniones.

1. No eres diligente, comprometido y responsable.

Si quieres pertenecer formalmente a nuestro grupo regístrate en [este
formulario](https://forms.gle/CXSkembQwAVbAnC5A).

## Más información

1. [¿Cómo preparar la exposición para el Club de
   Revista?](members/instrucciones-cdr.qmd)
