---
title: 'Material educativo'
subtitle: 'Biología Computacional y Bioinformática en Español'

listing:
  - id: edu
    contents: "material-educativo/**/index.qmd"
    type: grid
    sort-ui: true
    filter-ui: true

  - id: tutoriales
    contents:
      - "tutoriales/**/*{.qmd,md,yml}"
      - "../posts/2023/instalación-linux.md"
    type: grid
    sort-ui: true
    filter-ui: true
---

:::{#edu}
:::

# Tutoriales

:::{#tutoriales}
:::

# Recursos externos

A continuación encontrarás una lista de materiales educativos que hemos
encontrado útiles e interesantes.

## General

{{<fa globe>}} [Cursos del EBI-EMBL](https://www.ebi.ac.uk/training/)\
{{<fa globe>}} [Guías de ELIXIR y mejores prácticas para trabajar con datos
biológicos](https://elixir-europe.org/what-we-offer/guidelines)\
{{<fa globe>}} [Herramientas para Biología
Computacional](https://elixir-europe.org/what-we-offer/portals)\
{{<fa globe>}} [Buscador de cursos, eventos, videos, presentaciones, manuales y
mucho más](https://tess.elixir-europe.org/)\
{{<fa globe>}} [Material educativo del NCBI](https://www.ncbi.nlm.nih.gov/home/learn/)\

## Biología estructural

{{<fa brands youtube>}} [Curso de PyMOL](https://youtu.be/2UJ9_cADkek)\
{{<fa globe>}} [Dinámica molecular con GROMACS](http://www.mdtutorials.com/gmx/)\
{{<fa globe>}} [Curso de
AlphaFold](https://www.ebi.ac.uk/training/online/courses/alphafold/)

## RNA-seq

{{< fa brands youtube >}} [Workshop RNA-seq
UCLA](https://youtu.be/OO4PGQxACuk)\
{{<fa globe>}} [Análisis de datos de RNA-seq con DESeq2](https://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html)\
{{<fa globe>}} [RNA-seq Tutorial (with Reference Genome)](https://bioinformatics.uconn.edu/resources-and-events/tutorials-2/rna-seq-tutorial-with-reference-genome/)\
{{<fa brands youtube>}} [DESeq2 para principiantes](https://www.youtube.com/watch?v=0b24mpzM_5M)\
{{<fa globe>}} [Differential expression with DEseq2](https://genviz.org/module-04-expression/0004/02/01/DifferentialExpression/)

### Single cell RNA-seq

{{<fa brands youtube>}} [Introducción al single cell RNA-seq](https://youtu.be/_ND6pEsf5Kg)\
{{<fa brands youtube>}} [Análisis de single cell RNA-seq con Python](https://youtu.be/jwSPTgF9ESQ)\
{{<fa brands youtube>}} [Complete single-cell RNAseq analysis walkthrough](https://youtu.be/uvyG9yLuNSE)\
{{<fa globe>}} [Curso sobre análisis de datos de single cell RNA-seq](https://www.singlecellcourse.org/)

## Linux

{{<fa globe>}} [The Linux command line for beginners](https://ubuntu.com/tutorials/command-line-for-beginners)

## Bases de datos

{{<fa globe>}} [Databases and SQL](https://swcarpentry.github.io/sql-novice-survey/)

## Filogenética

{{<fa globe>}} [Tutoriales y cursos de bioinformática y filogenética en
Español](https://www.ccg.unam.mx/~vinuesa/Tutoriales_y_cursos_bioinfo_filogen%C3%A9tica_espa%C3%B1ol_PV.html)
