---
title: Consejos para preparar el Club de Revista
---

Ten en cuenta los siguientes consejos para escoger el artículo que
presentarás en el Club de Revista:

1. **Elige un artículo relevante.** Esto quiere decir que el artículo esté
   cercanamente relacionado con el proyecto con el que estés trabajando, o
   donde usen métodos que sean de interés. La idea es que la lectura y
   exposición del artículo te nutran y te permitan aprender.

2. **Elige un artículo preferiblemente de los últimos 5 años.** Esta no es una
   regla absoluta, porque también hay artículos que es importante discutir y
   que son más viejos, pero idealmente uno de los objetivos del Club de
   Revista es mantenerse actualizado con la literatura más reciente.

3. **Revisa que el artículo sea de buena calidad.** Esto generalmente implica
   leer o darle un vistazo al artículo. A veces conviene fijarse en qué
   revista fue publicado, aunque muy buenos artículos son publicados en
   revistas malas, y también artículos muy malos son publicados en revistas
   prestigiosas.

4. **Lee el artículo con antelación.** Comprender un artículo académico y
   sus métodos, y preparar una exposición sobre ello no es algo que pueda
   hacerse fácilmente en una semana o dos, asegúrate de elegir y leer el
   artículo con al menos un mes de anticipación a la fecha de la exposición.
   Lee el artículo mínimo dos veces para entenderlo bien.
